### ISSUE TITLE
Do you know any algorithm in F#? 

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/fsharp#2]
<p align="center">
  <img src="https://cdn.abraham.gq/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [F#](https://github.com/AllAlgorithms/fsharp) this case

**Comment by dinx6** [comment]
Yeah. We added quite algorithms in the past few weeks. Can you please verify and merge them ?
